### ISSUE TITLE
Option to load  SummarizedExperiment directly from browser

### ISSUE THREAD

**Issue by annaquaglieri16** [csoneson/iSEE#299] opened 2019-06-26 20:42 UTC
Hi there, 

Awesome work! My suggestion is that it would be good to be able to load an R SummarizedExperiment object directly from the app. My experience with some busy and maybe more senior biologists/clinicians is that they don't want to deal with R (even after I downloaded it for them). 

In this way, bioinformaticians would only need to share the SummarizedExperiment object with collaborators and they would have to simply upload it and explore it. 

Thanks!

Anna

**Comment by csoneson** [comment] 2019-06-26 20:48
Hi Anna! We have thought about this previously, and decided to not support it at this stage. The reasoning can be found in #213.

**Comment by kevinrue** [comment] 2019-06-27 02:49
In addition, installing a Shiny server (https://www.rstudio.com/products/shiny/shiny-server/) on your side or with you IT team can completely remove the need for users to install _anything_.
For instance, the Marioni group hosts our 4 demo apps which anyone can open in a web-browser without any pre-requisite on their side, it's all running on the server in Cambridge:
https://marionilab.cruk.cam.ac.uk

**Comment by LTLA** [comment] 2019-06-27 06:53
Agree with Kevin here. Let's say that, hypothetically, we did support this uploading feature. (Which, BTW, would not be easy.) It would still require the analyst to have the capacity to produce the SE object; send the SE to the collaborators; and have the collaborators manually upload the SE to an iSEE instance hosted on a Shiny server somewhere. If we're talking clinical data, this Shiny server would have to be local for privacy/GDPR/etc. reasons, which suggests that you should be able to get access to it.

At this point, it is not much of a stretch to cut out part of the loop and just create an iSEE instance on the Shiny server that uses whatever SE you produced. This means that your collaborators simply have to go to the URL - no transferring of files, no uploading - and they can play around with it to their heart's content.

**Comment by federicomarini** [comment] 2019-06-27 07:50
The others said it all already, but the bottom line is as Kevin put it in the lightning talk:
iSEE, and setting up instances on a Shiny server, really can work out of the box 😎

**Comment by kevinrue** [comment] 2019-06-27 13:51
... and with all 4 developers having commented, I think we're good to close the issue  😆

**Comment by annaquaglieri16** [comment] 2019-06-28 03:39
Hi there, 
Thanks for all your replies. I am just talking out of personal experience (with 2 doctors though). I know you closed the issue but I will share my experience:
- I created a summary table of the data and shared it as csv.
- They always came back with new pictures requests 
- I made a very easy Shiny app to explore a cvs file with embedded the clinical data. Downloaded R on their computer and shown how to do it several times (click runApp). 
- They never used it. 
- I un-embedded the data https://shiny.wehi.edu.au/quaglieri.a/shiny-clone/ and therefore I was able to host it on our institute servers (they would not host clinical data, that would require more effort on restricting access, mainly from my side, or ITs? not sure)  
- Now I save the csv file in an easy location and they are using the app. We always use it for meetings, they are really happy with it. Of course, they want more, but that was a good start. 

However, this is just my experience really. It depends who the app is aimed for, of course. The clinicians/more senior biologists that I am working with would not make the effort to go and open R by themselves. Maybe more junior researchers would!

Cheers,
Anna

**Comment by annaquaglieri16** [comment] 2019-06-28 03:41
On the other hand, it's an awesome tool to share the data publicly, once they are published as you are showing in Marioni's group!

**Comment by LTLA** [comment] 2019-06-28 07:00
I have some comments about this but first I need to sleep.

**Comment by LTLA** [comment] 2019-06-28 18:43
This may actually be surprisingly easy. 

1. Move all observer initialization in the server function into another internal function `X`.
2. Call `X` at the top of the server function - this mimics what we already do.
3. Add a UI element to upload an SE, with an observer inside `X`.
4. That observer then calls `X` if it gets triggered to re-initialize all observers.

This assumes that we can move the observers into a different event environment, so some care is required to set that up properly. But in theory, it should be relatively doable, and would be a good opportunity to split up the monolithic `iSEE` function definition into more digestible parts.

**Comment by kevinrue** [comment] 2019-06-29 17:38
I’m on my phone so I’ll stay brief.
It is attractive, and I think possible, to be able to implement this feature. That said, i do remain somewhat nervous at the idea that users would be able to ‘hijack’ an app (E.g., Demo, published dataset) and load their own data in a session that was intended to be “read only”.
Bottom line is that if we do implement that feature, i suggest that it put under the control of a logical ‘iSEE(..., customSCE=TRUE)’ so that FALSE would hide the upload button/feature to behave as it does currently.

**Comment by LTLA** [comment] 2019-06-29 17:39
Yes, if the `se` is provided from the console, this option is not available. It only gets active if the input `se` was missing.

**Comment by annaquaglieri16** [comment] 2019-06-29 21:10
Thank @LTLA! I think it would be really helpful.  And yes, I agree with you @kevinrue, I wouldn't let any data be uploaded in those circumstances. But, what I am suggesting is to allow interactive exploration of new data while the analyses are still going on.

**Comment by LTLA** [comment] 2019-06-30 07:43
Well, I can't say it was easy, but it's done.

**Comment by LTLA** [comment] 2019-07-18 02:35
Closed by #300.

**Closed by LTLA** 2019-07-18 02:35 UTC
