### ISSUE TITLE
‘overview first, zoom & filter, details on demand

### ISSUE THREAD

**Issue by davismcc** [csoneson/iSEE#63] opened 2018-01-19 16:55 UTC
‘overview first, zoom & filter, details on demand’ is the ‘Visual Information-Seeking Mantra’ for large datasets - we should apply this!

**Comment by kevinrue** [comment] 2018-01-19 18:14
as discussed, density-dependent downsampling might help here

**Comment by LTLA** [comment] 2018-01-19 18:22
Combined with shiny's zooming ability, https://shiny.rstudio.com/gallery/plot-interaction-zoom.html

**Comment by kevinrue** [comment] 2018-01-20 23:59
to track progress:
the 'zoom' feature was implemented to some extent by the 'brush to restrict' feature in 8c8ba4310e22287112e39f2a30e320a4d0acffbe

**Comment by LTLA** [comment] 2018-01-21 00:03
Though this requires (i) there to be selected points (as the restriction will collapse the boundaries to the bounding box of the selected points) and (ii) that the plot is receiving its own brush. There is also the annoying behaviour that it's not easy to unzoom due to how we've implemented the brushing here.

We will probably have to formally set up zooming capabilities, probably with an option to turn it off as well for people who just want to brush from the plot and not have to worry about zooming.

**Comment by csoneson** [comment] 2018-01-21 07:14
For the unzooming, could we add an option 'Receive brush from: "None"', which resets the plot to original axes?

**Comment by kevinrue** [comment] 2018-01-21 11:10
@csoneson : in my mind, unticking 'transmit brush' should do that already. 
Testing it now makes me realise that somehow unticking 'transmit brush' still applies the latest recorded brush. Needs looking into, I think.

**Comment by csoneson** [comment] 2018-01-21 11:15
Yeah, to me it just seems more intuitive to disable/remove the "incoming" brush (what is applied to this particular plot) than the "outgoing"/transmitted brush (since that may still be applied to other plots).

**Comment by kevinrue** [comment] 2018-01-21 11:26
@csoneson : partially fixed in f8bc353 
The incoming brush is disabled in the 'receiving' plot when 'transmit brush' is unticked.
However, when ticked again, it applies against the latest brushed received even though the brushing effect is no longer visible in the 'sending' plot.

**Comment by LTLA** [comment] 2018-01-21 12:30
I think we're overthinking this. Restrict and zooming considerations are different, for reasons I've discussed above. I'm sure we can manually add a zoom feature, based on the link I put in earlier.

To that end, I believe that "Restrict" should actually retain the original coordinates. Zooming will be handled separately.

**Comment by LTLA** [comment] 2018-01-21 14:43
Also, f8bc353085cf8eedd13f14d9d9cdcc3c978374a5 doesn't do as intended; it means that a plot will only respond to brushing if it itself is a transmitter, which shouldn't be the case.

**Comment by LTLA** [comment] 2018-01-21 17:02
Done for scatter plots (2ab4ed2bd54c500109536c15e8b109458459b591), using the mechanism in https://shiny.rstudio.com/gallery/plot-interaction-zoom.html. Brush first, double click inside the brush to zoom, outside the brush to revert back to the original. It should be easy enough to extend to other plots.

**Comment by LTLA** [comment] 2018-01-22 15:30
Done in #65, closing.

**Closed by LTLA** 2018-01-22 15:30 UTC
